// Auto-generated by olova-router - DO NOT EDIT
// This file is auto-updated when you add/remove route folders

import { createLink, OlovaRouter, useRouter, useParams, useSearchParams, Outlet } from 'olova-router/router';
import Route0 from './App';
import Route1 from './about/index';
import Route2 from './(auth)/login/index';
import Route3 from './(auth)/register/index';
import Route4 from './search/index';
import Route5 from './users/index';
import Route6 from './blog/$/index';
import Route7 from './users/$id/index';
import NotFound0 from './404';
import Layout0 from './_layout';

export const routes = [
  { path: '/', component: Route0 },
  { path: '/about', component: Route1 },
  { path: '/login', component: Route2 },
  { path: '/register', component: Route3 },
  { path: '/search', component: Route4 },
  { path: '/users', component: Route5 },
  { path: '/blog/*', component: Route6 },
  { path: '/users/:id', component: Route7 }
];

export const notFoundPages = [
  { pathPrefix: '', component: NotFound0 }
];

export const layouts = [
  { path: '/', layout: Layout0, children: [] }
];

export type RoutePaths = '/' | '/about' | '/login' | '/register' | '/search' | '/users' | '/blog/*' | '/users/:id';

export const Link = createLink<RoutePaths>();
export { OlovaRouter, useRouter, useParams, useSearchParams, Outlet };
export type { NotFoundPageConfig, SearchParams, SetSearchParamsOptions, LayoutRoute } from 'olova-router/router';
